// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgyffvpwrisekxtpclmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneWZmdnB3cmlzZWt4dHBjbG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzM5NjUsImV4cCI6MjA2ODYwOTk2NX0.cEoVxE1-TF6YzwRqCvAts-PwyIQNpzEt3S_igDPSv_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});